import type { Metadata } from "next";
import { BackgroundDecorations } from "@/components/ui/background-decorations";
import { Inter } from "next/font/google";
import "./globals.css";
import ConditionalNavbar from "./ConditionalNavbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "HashBoot",
  description: "Generated by HashBoot",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased font-inter`}
      >
        <BackgroundDecorations />
        <ConditionalNavbar>
          {children}
        </ConditionalNavbar>
      </body>
    </html>
  );
}
