import type { Metadata } from "next";
import { BackgroundDecorations } from "@/components/ui/background-decorations";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "HashBoot",
  description: "Generated by HashBoot",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <BackgroundDecorations />
        <Navbar/>
          {children}
      </body>
    </html>
  );
}
